### ISSUE TITLE
Got an error when I have a table with an array column

### ISSUE THREAD

**Issue by gstoffer** [arkhipov/temporal_tables#8]
CONFIGS :
PostgreSQL 9.4
Temporal_tables 1.0.2

Hi,

I  have an issue when I use a versioned table contains an array column like this :

CREATE TABLE example (
id serial PRIMARY KEY,
name text,
url text,
enabled boolean DEFAULT true,
tags text[],
sys_period tstzrange NOT NULL DEFAULT tstzrange(current_timestamp, null)
);

CREATE TABLE example_history (LIKE example);

CREATE TRIGGER versioning_example_trigger
BEFORE INSERT OR UPDATE OR DELETE ON example
       FOR EACH ROW EXECUTE PROCEDURE versioning('sys_period', 'example_history', true);

INSERT INTO example VALUES (DEFAULT, 'john', 'http://www.example.com', true, ARRAY['doe', 'John'], DEFAULT);

DELETE FROM example WHERE id = 1;

When I DELETE on this table I got this error :
column "tags" of relation "example" is of type text[] but column "tags" of history relation "example_history" is of type text[]

regards,

Guillaume STOFFER

**Comment by arkhipov** [comment]
Hello, @gstoffer.

The issue you are encountering was already [reported](http://www.postgresql.org/message-id/20150707072942.1186.98151@wrigleys.postgresql.org) on the PostgreSQL mailing list on July 7, 2015. I am not sure if there has been any progress since then, but it might be a good idea to ask them.

As a workaround, you can create the history table without using `LIKE/AS`.

**Comment by gstoffer** [comment]
Hello,

Many thanks for the answer and the workaround. :-)

**Comment by gstoffer** [comment]
Hello,

As this is not a bug in your project, I close this ticket.

Regards :-)
